/**
 * SofaScore numeric team IDs for WC 2026 nations.
 * Generated by scripts/bootstrap-team-sofa-ids.mjs — re-run to refresh.
 */
export const TEAM_SOFA_IDS: Record<string, number> = {
  "ALG": 4691,
  "ARG": 4819,
  "AUS": 4741,
  "AUT": 4718,
  "BEL": 4717,
  "BIH": 4479,
  "BRA": 4748,
  "CAN": 4752,
  "CIV": 933582,
  "COD": 4823,
  "COL": 4820,
  "CPV": 4753,
  "CRO": 4715,
  "CUW": 55827,
  "CZE": 522579,
  "ECU": 4757,
  "EGY": 4758,
  "ENG": 4713,
  "ESP": 4698,
  "FRA": 4481,
  "GER": 4711,
  "GHA": 4764,
  "HAI": 7229,
  "IRN": 4766,
  "IRQ": 4767,
  "JOR": 4771,
  "JPN": 4770,
  "KOR": 4735,
  "KSA": 4834,
  "MAR": 4778,
  "MEX": 4781,
  "NED": 4705,
  "NOR": 4475,
  "NZL": 4784,
  "PAN": 5164,
  "PAR": 4789,
  "POR": 4704,
  "QAT": 4792,
  "RSA": 4736,
  "SCO": 4695,
  "SEN": 4739,
  "SUI": 4699,
  "SWE": 4688,
  "TUN": 4729,
  "TUR": 528538,
  "URU": 4725,
  "USA": 487953,
  "UZB": 4723
};

export function resolveSofaTeamId(abbrev: string): number | undefined {
  return TEAM_SOFA_IDS[abbrev.toUpperCase()];
}
